apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django

spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: rzmobiledev/django:v1
          ports:
            - containerPort: 8000

          env:
            - name: HOST
              value: postgres-service
            
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DEBUG
            
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: POSTGRES_DB
            
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DB_PORT
            
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: postgres_user
            
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: postgres_password
            
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: secret_key

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30100