apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  postgres_user: cnptb2JpbGVkZXY=
  postgres_password: cnptb2JpbGVkZXZAZ21haWwuY29tX3Bhc3N3b3Jk
  secret_key: Y25wdGIySnBiR1ZrWlhaQVoyMWhhV3d1WTI5dFgzQmhjM04zYjNKa1NlY3JldCUjS2V5